### ISSUE TITLE
Two question for documentation

### ISSUE THREAD

**Issue by xavgit** [forlilab/Ringtail#61] opened 2024-11-19 09:21 UTC
Hi,
in the documentation ( https://ringtail.readthedocs.io/en/stable/index.html )
in the **command line interface section** there is the following statement:
_"Be cautious when adding results from multiple screening runs, since some target information is checked and some is not."_
It is possible to receive some examples about what I should be cautious?
For the scatterplot in the section **Create scatterplot highlighting ligands passing filters** it 
is possible to describe what it is its meaning?
For example the reasons why there are red, blue and green circles?
Sorry, I don't have any experience with this type of plot.

Many thanks.

Saverio

**Comment by diogomart** [comment] 2024-11-19 22:50
Hi,
Just replying to your first question here, and maybe @maylinnp or @althea-hansel can elaborate or correct what I'm writing. Ringtail tail was designed to have one receptor, not more, per database. The interactions with the receptor are filtered using chain ID and residue numbers, thus conflicts would be nearly unavoidable if results originate from multiple receptors. But it is impossible to guarantee that docking results originate from a single receptor because the docking output files (".dlg" from autodock-gpu or ".pdbqt" from vina) do not have enough information for that.

**Comment by xavgit** [comment] 2024-11-20 15:32
Hi,
thanks for the reply.
Sorry for the request of the meaning of the red circles as I had missed the 
line in the documentation where there was the explanation.
If possible, another question.
Can be planned for Vina the output of the docking results in .dlg format?
In this format there are the cluster histogram and rmsd table sections 
that provide interesting informations and , also, the processing with ringtail 
can be made in more uniform way.

Thanks.

Saverio

**Comment by diogomart** [comment] 2024-11-20 16:43
That would have been nice from the start, but now many people expect PDBQT out of vina, if we changed that it would be backwards incompatible. Also Vina doesn't store clustering data internally.

**Comment by maylinnp** [comment] 2024-11-26 18:55
Hi @xavgit and sorry for my slow response. Regarding receptor I agree that the statement is ambiguous, and I added the following statement: "Be cautious when adding results from multiple screening runs. Ringtail only allows one receptor per database, and will do this by checking that the receptor name is the same. However, if you do multiple screens with e.g., different binding pockets for the same receptor, this information will not be checked, and Ringtail will allow any data to be appended to a database as long as the receptor name is the same."

**Comment by maylinnp** [comment] 2024-11-26 19:17
@xavgit regarding the scatterplot I will work on adding some better descriptions and labels. Since it might take me a few days to get through, the gradient colored dots are not representing single data points but rather data binned by the two axes, and the color represents how many single data points are in that bin (that point is further reinforced by the histograms which sums per line in either dimension). 
The red points are individual data points for any ligands that passed the filter you specified while producing the plot.

**Comment by maylinnp** [comment] 2024-12-06 18:21
Fixed in commits 3d3c7ee, 99c0f20, and d74220a, will be in the next release. 
The plot also comes with improved looks that should clarify what is what, the plot method can return a matplotlib.figure object handle, and an extra API method has been added to get the plot data.

**Closed as completed by maylinnp** 2024-12-06 18:21 UTC
